name: build and run tests
# https://github.com/avsm/setup-ocaml

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-version:
          - 4.04.2
          - 4.05.0
          - 4.06.1
          - 4.07.1
          - 4.08.1
          - 4.09.1
          - 4.10.1
          - 4.11.2
          - 4.12.0


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache # https://github.com/marketplace/actions/cache
        uses: actions/cache@v2.0.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.opam
            _opam
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-new-${{ matrix.ocaml-version }}

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add goblint-cil.dev . --no-action
      - run: opam depext goblint-cil --yes
      - run: opam depext goblint-cil --yes --with-doc
      - run: opam depext goblint-cil --yes --with-test
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
